NGO/urls.py
from django.contrib import admin
from django.conf.urls import include,url
from django.contrib.auth import login, logout
from django.views.static import serve
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

from User import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('Event.url')),
    url(r'^login/$', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
    #url(r'^login/$', auth_view.LoginView.as_view(template_name='registration/login.html'), name='login'),
    #url(r'^logout/$', auth_view.LogoutView.as_view(template_name='User/logout.html'), name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^', include('User.urls', namespace='User')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

User/urls.py
from django.conf.urls import url
from User import views


app_name = 'Myuser'

urlpatterns = [
    #url('', HomePageView.as_view() , name='login'),
    url('user/', views.user_list, name='user_list' ),
    url('new/', views.user_new, name='user_new'),
    url('delete/(?P<pk>\d+)', views.user_delete, name='user_delete'),
    url('edit/(?P<pk>\d+)', views.user_edit, name='user_edit'),
]

User/models.py
from django.db import models

class Myuser(models.Model):
    firstName = models.CharField(max_length=50)
    lastName = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)
    username = models.CharField(max_length=50, default="")
    password = models.CharField(max_length=50)
    role = models.CharField(max_length=50)


    def __str__(self):
        return self.lastName

User/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import TemplateView
from django.contrib.auth.models import User

from .models import Myuser
from .form import UserForm


#@login_required
def user_list(request):
    users = Myuser.objects.all()
    adminusers = Myuser.objects.filter(role='admin')
    allusers = Myuser.objects.all()
    return render(request, 'User/user_list.html', {'users':users,'adminusers':adminusers,'allusers':allusers})

def user_new(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password')
            email = form.cleaned_data.get('email')
            user = form.save()
            #login(request, user,backend='django.contrib.auth.backends.ModelBackend')
            users = Myuser.objects.all()
            User.objects.create_user(username=username, password=raw_password, email=email)
            return render(request, 'User/user_list.html', {'users':users})
    else:
        form = UserForm()
        return render(request, 'User/user_edit.html', {'form': form})

def user_delete(request, pk):
    user = get_object_or_404(Myuser, pk=pk)
    user.delete()
    messages.success(request, "User successfully deleted!")
    return HttpResponseRedirect("/user/")


    #return render(request,'User/user_list.html', {'user':user})

def user_edit(request, pk):
    user = get_object_or_404(Myuser, pk=pk)
    if request.method == "POST":
        form = UserForm(request.POST, instance=user)
        if form.is_valid():
            user = form.save(commit=True)
            username = form.cleaned_data.get('username')
            newpassword = form.cleaned_data.get('password')
            email = form.cleaned_data.get('email')
            try:
                User.objects.get(username=username)
            except:
                User.objects.filter(username=username).delete()
                User.objects.create_user(username=username, password=newpassword, email=email)
            else:
                user1 = User.objects.get(username=username)
                user1.set_password(newpassword)
                user1.save()
            return HttpResponseRedirect("/user/")
    else:
        form = UserForm(instance=user)
        return render(request, 'User/user_edit.html', {'form': form})


def signup(request):
    #if request.method == 'POST':
    #    form = UserCreationForm(request.POST)
    #    if form.is_valid():
    #        form.save()
    #        username = form.cleaned_data.get('username')
    #        raw_password = form.cleaned_data.get('password1')
    #        user = authenticate(username=username, password=raw_password)
    #        login(request, user)
    #        return HttpResponseRedirect("/user/")
    #else:
    #    form = UserCreationForm()
    #return render(request, 'User/signup.html', {'form': form})
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password')
            email = form.cleaned_data.get('email')
            user = form.save()
            #login(request, user,backend='django.contrib.auth.backends.ModelBackend')
            users = Myuser.objects.all()
            User.objects.create_user(username=username, password=raw_password, email=email)
            return render(request, 'User/user_list.html', {'users':users})
    else:
        form = UserForm()
        return render(request, 'User/user_edit2.html', {'form': form})

User/templates/User/logout.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2> You have been logged out!</h2>
<div>
    <small>
        <button><a href="{% url 'login' %}">Log in again</a></button>
    </small>
</div>
</body>
</html>
{% endblock %}

User/templates/User/signup.html
{% extends 'base2.html' %}



 {% block content %}

  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>

{% endblock %}

User/templates/User/user_delete.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h3> are you sure you want to delete </h3>
</body>
</html>
{% endblock %}

User/templates/User/user_edit.html
{% extends 'base.html' %}

{% block content %}

<div class="content">
    <h2>New user</h2>
    <form method="POST" class="user-form">
        <table>
        {% csrf_token %}
        {{ form.as_table }}
            </table>
        <button type="submit" >Save</button>
        <button type="cancel"><a href="{% url 'User:user_list' %}">Cancel</a></button>

    </form>
</div>
{% endblock %}

User/templates/User/user_edit2.html
{% extends 'base2.html' %}

{% block content %}

<div class="content">
    <h2>New user</h2>
    <form method="POST" class="user-form">
        <table>
        {% csrf_token %}
        {{ form.as_table }}
            </table>
        <button type="submit" >Save</button>
        <button type="cancel"><a href="{% url 'User:user_list' %}">Cancel</a></button>

    </form>
</div>
{% endblock %}

User/templates/User/user_list.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block content %}

    {% for u in adminusers %}
    {% if user.username == u.username %}
<div class="content">
  <div style="background-color:#EEEEEE;height:50px;width:1200px;">
    <h1>User Management</h1></div>
    <h2><a href="{% url 'User:user_new' %}" style="float:right"  >Add User</a></h2>

  <table  border="1">
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Email</th>
    <th>Role</th>
    <th></th>
    <th></th>
  </tr>

   {% for obj in users %}
  <tr>
    <td>{{obj.firstName}}</td>
    <td>{{obj.lastName}}</td>
    <td>{{obj.email}}</td>
    <td>{{obj.role}}</td>
      <td><a href="{% url 'User:user_edit' pk=obj.pk %}">Edit</a></td>
    <td><a href="{% url 'User:user_delete' pk=obj.pk %}" onclick="return confirm('Are you sure you want to delete this?')"> delete</a></td>
  </tr>
   {% endfor %}
  </table>

</div>
{% endif %}
{% endfor %}

{% endblock %}